name: WSL Tarball Build (sysspc)
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Tarball
      run: sudo nix run .#nixosConfigurations.sysspcdx.config.system.build.tarballBuilder
    - name: Release Tarball
      uses: softprops/action-gh-release@v2
      with:
        files:
          - nixos-wsl.tar.gz
